# Loading the cases that are not in per unit and generating base load 

In [5]:
import numpy as np
import pandas as pd
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus

PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"

TEST_CASE = '906'

def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")

    bus = mat['ans']['bus'][0][0]
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc

#def convert_branch(baseMVA, bus, branch):
#    Vbase = bus[0, 7] * 1e3  # Vbase = mpc.bus(1, BASE_KV) * 1e3; in Volts
#    Sbase = baseMVA * 1e6  # Sbase = mpc.baseMVA * 1e6; in VA
#    branch[:, [2, 3]] = branch[:, [2, 3]] / (Vbase**2 / Sbase)  # convert branch impedance

def convert_loads(bus):
    bus[:, [2, 3]] = bus[:, [2, 3]] / 1e3  # convert loads from kW to MW

def calculate_just_loads(baseMVA, bus):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses = Just_load[:, 0]
    load_buses = np.reshape(load_buses, (len(load_buses), 1))

    P_Load = Just_load[:, 2] / baseMVA
    Q_Load = Just_load[:, 3] / baseMVA
    P_load = np.reshape(P_Load, (len(load_buses), 1))
    Q_load = np.reshape(Q_Load, (len(load_buses), 1))

    return P_load, Q_load

# Example usage:
baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()
#convert_branch(baseMVA, bus, branch)
"""Convert loads to MW if they are in kW"""
#convert_loads(bus)
P_load, Q_load = calculate_just_loads(baseMVA, bus)

# Now you can use P_load, Q_load, and other modified arrays as needed.


In [2]:
P_load

array([[5.7400e-06],
       [4.4000e-07],
       [1.1400e-06],
       [2.3100e-06],
       [3.5000e-07],
       [3.9500e-06],
       [5.5000e-07],
       [2.8360e-05],
       [1.3100e-06],
       [2.7980e-05],
       [4.9000e-07],
       [2.8600e-06],
       [2.2110e-05],
       [2.1000e-06],
       [2.3310e-05],
       [5.1000e-06],
       [4.8000e-07],
       [4.1100e-06],
       [4.5700e-06],
       [5.1000e-07],
       [4.5000e-07],
       [5.4000e-07],
       [2.3600e-06],
       [7.5000e-07],
       [2.3400e-06],
       [1.2659e-04],
       [1.5500e-06],
       [2.8000e-07],
       [1.0471e-04],
       [5.3000e-07],
       [2.2830e-05],
       [6.0600e-06],
       [3.0300e-06],
       [5.8000e-07],
       [5.5700e-05],
       [1.5600e-06],
       [1.0630e-05],
       [3.9200e-06],
       [4.8000e-07],
       [4.2700e-06],
       [6.5000e-07],
       [3.6600e-06],
       [5.0000e-07],
       [1.6770e-05],
       [1.7300e-06],
       [4.9000e-07],
       [4.5000e-07],
       [2.141

# Loading the 123 case because it is already in per unit

In [15]:
import numpy as np
import pandas as pd
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus
import numpy as np
import matplotlib.pyplot as plt
PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"

TEST_CASE           =   'IEEE123'
#TEST_CASE           =   '_small'
#TEST_CASE           =   'small_negload'


def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")

    bus = mat['ans']['bus'][0][0]
    #print(bus)
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc

baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()


def calculate_just_loads (baseMVA, bus):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses=Just_load[:,0]
    load_buses=np.reshape(load_buses,(len(load_buses),1))
    # this is done automatically when using ext2int
    #P_Load  = Just_load [:,2]/baseMVA
    #Q_Load  = Just_load [:,3]/baseMVA
    P_Load  = Just_load [:,2]  #"""Just for the small cases where load were nultiplied by 2"""
    Q_Load  = Just_load [:,3]
    P_load  = np.reshape(P_Load,(len(load_buses),1))    
    Q_load  = np.reshape(Q_Load,(len(load_buses),1)) 

    return P_load, Q_load

In [16]:
P_load, Q_load = calculate_just_loads (baseMVA, bus)
P_load

array([[0.04 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.02 ],
       [0.02 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.02 ],
       [0.105],
       [0.21 ],
       [0.14 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.04 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.02 ],
       [0.04 ],
       [0.04 ],
       [0.075],
       [0.14 ],
       [0.075],
       [0.02 ],
       [0.04 ],
       [0.02 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.245],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [0.04 ],
       [

# Constant PF scenario generation


In [3]:
import numpy as np
baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()

"""turn this on for 33 bus but not for cases where it is already in MW"""
#convert_loads(bus)

P_load, Q_load = calculate_just_loads (baseMVA, bus)
print(P_load)
N=1000
def generate_scenarios(P_load, Q_load, N):
    # Calculate the initial power factor
    power_factor = P_load / np.sqrt(P_load**2 + Q_load**2)

    # Initialize the scenarios matrix
    P_load_scenarios = np.zeros((N, P_load.shape[0]))
    Q_load_scenarios = np.zeros((N, Q_load.shape[0]))

    # For every non-zero element in P_load, generate N scenarios.
    # Then calculate corresponding Q_load scenarios to maintain power factor
    for idx in range(P_load.shape[0]):
        if P_load[idx, 0] != 0:
            P_load_scenarios[:, idx] = np.random.normal(P_load[idx, 0], abs(0.35 * P_load[idx, 0]), N)
            # Calculate Q for each P scenario while keeping power factor constant
            Q_load_scenarios[:, idx] = P_load_scenarios[:, idx] * np.tan(np.arccos(power_factor[idx, 0]))

    return P_load_scenarios, Q_load_scenarios

def generate_scenarios_neg(P_load, Q_load, N):
    # Calculate the initial power factor
    power_factor = P_load / np.sqrt(P_load**2 + Q_load**2)

    # Initialize the scenarios matrix
    P_load_scenarios = np.zeros((N, P_load.shape[0]))
    Q_load_scenarios = np.zeros((N, Q_load.shape[0]))

    # For every non-zero element in P_load, generate N scenarios.
    # Then calculate corresponding Q_load scenarios to maintain power factor
    for idx in range(P_load.shape[0]):
        if P_load[idx, 0] != 0:
            P_load_scenarios[:, idx] = np.random.normal(-P_load[idx, 0], abs(0.35 * P_load[idx, 0]), N)
            # Calculate Q for each P scenario while keeping power factor constant
            Q_load_scenarios[:, idx] = P_load_scenarios[:, idx] * np.tan(np.arccos(power_factor[idx, 0]))

    return P_load_scenarios, Q_load_scenarios


P_load_scenarios_pos, Q_load_scenarios_pos = generate_scenarios(P_load, Q_load, N)
P_load_scenarios_neg, Q_load_scenarios_neg = generate_scenarios_neg(P_load, Q_load, N)

P_load_scenarios = np.concatenate ((P_load_scenarios_pos,P_load_scenarios_neg))
Q_load_scenarios = np.concatenate ((Q_load_scenarios_pos,Q_load_scenarios_neg))


np.save(f"{PATH}/data/P_load_all_scenarios_{TEST_CASE}bus.npy", P_load_scenarios)
np.save(f"{PATH}/data/Q_load_all_scenarios_{TEST_CASE}bus.npy", Q_load_scenarios)

[[5.7400e-06]
 [4.4000e-07]
 [1.1400e-06]
 [2.3100e-06]
 [3.5000e-07]
 [3.9500e-06]
 [5.5000e-07]
 [2.8360e-05]
 [1.3100e-06]
 [2.7980e-05]
 [4.9000e-07]
 [2.8600e-06]
 [2.2110e-05]
 [2.1000e-06]
 [2.3310e-05]
 [5.1000e-06]
 [4.8000e-07]
 [4.1100e-06]
 [4.5700e-06]
 [5.1000e-07]
 [4.5000e-07]
 [5.4000e-07]
 [2.3600e-06]
 [7.5000e-07]
 [2.3400e-06]
 [1.2659e-04]
 [1.5500e-06]
 [2.8000e-07]
 [1.0471e-04]
 [5.3000e-07]
 [2.2830e-05]
 [6.0600e-06]
 [3.0300e-06]
 [5.8000e-07]
 [5.5700e-05]
 [1.5600e-06]
 [1.0630e-05]
 [3.9200e-06]
 [4.8000e-07]
 [4.2700e-06]
 [6.5000e-07]
 [3.6600e-06]
 [5.0000e-07]
 [1.6770e-05]
 [1.7300e-06]
 [4.9000e-07]
 [4.5000e-07]
 [2.1410e-05]
 [5.4000e-07]
 [3.1000e-06]
 [5.3000e-07]
 [2.9500e-06]
 [3.0870e-05]
 [2.4500e-06]
 [5.5000e-07]]


In [12]:
TEST_CASE = '533'

P_load_all_scenarios_ = np.load(f"{PATH}/data/P_load_all_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)
P_load_all_scenarios_

array([[ 8.68220207e-04,  9.59902457e-05, -3.84844814e-04, ...,
         1.05451483e-03,  5.88683589e-04,  7.76829206e-04],
       [ 5.85307351e-04,  9.56902369e-05, -6.90366764e-04, ...,
         8.79445724e-04,  5.12702197e-04,  1.85029198e-03],
       [ 6.43585032e-04,  7.04931801e-05, -5.50454891e-04, ...,
         1.42952595e-03,  6.81168610e-04,  7.93646024e-04],
       ...,
       [-1.14673337e-03, -1.21509477e-04,  5.45500894e-04, ...,
        -6.24954260e-04, -9.05770547e-04, -9.82652836e-04],
       [-5.65929561e-04, -8.12297942e-05,  8.58104995e-04, ...,
        -1.82941314e-03, -5.91185276e-04, -1.03549808e-03],
       [-6.66563227e-04, -9.41354798e-05,  9.17028712e-04, ...,
        -1.85002622e-03, -6.31988923e-04, -1.07827623e-03]])

# Random scenario generation for P and Q

In [59]:
TEST_CASE           =   '22'

N=1000
def generate_scenarios(P_load, Q_load, N):
    # Initialize the scenarios matrix
    P_load_scenarios = np.zeros((N, P_load.shape[0]))
    Q_load_scenarios = np.zeros((N, Q_load.shape[0]))
    
    # For every non-zero element in P_load and Q_load, generate N scenarios using a normal distribution.
    for idx in range(P_load.shape[0]):
        if P_load[idx, 0] != 0:
            P_load_scenarios[:, idx] = np.random.normal(P_load[idx, 0], abs(0.45 * P_load[idx, 0]), N)
        if Q_load[idx, 0] != 0:
            Q_load_scenarios[:, idx] = np.random.normal(Q_load[idx, 0], abs(0.45 * Q_load[idx, 0]), N)
    
    return P_load_scenarios, Q_load_scenarios

P_load_scenarios, Q_load_scenarios = generate_scenarios(P_load, Q_load, N)
np.save(f"{PATH}/data/P_load_all_scenarios_{TEST_CASE}bus.npy", P_load_scenarios)
np.save(f"{PATH}/data/Q_load_all_scenarios_{TEST_CASE}bus.npy", Q_load_scenarios)

# For 141 bus case which is differnt and only has MVA data

In [29]:
import numpy as np
import pandas as pd
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus

PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"

TEST_CASE = '141'

def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")

    bus = mat['ans']['bus'][0][0]
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)
    
    """Only For 141 bus case which is differnt and only has MVA data"""
    pf = 0.85
    bus[:, 3] = bus[:, 2] * np.sin(np.arccos(pf))  # MVA to MVAr
    bus[:, 2] = bus[:, 2] * pf  # MVA to MW
    

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc



def convert_loads(bus):
    bus[:, [2, 3]] = bus[:, [2, 3]] / 1e3  # convert loads from kW to MW

def calculate_just_loads(baseMVA, bus):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses = Just_load[:, 0]
    load_buses = np.reshape(load_buses, (len(load_buses), 1))

    P_Load = Just_load[:, 2] / baseMVA
    Q_Load = Just_load[:, 3] / baseMVA
    P_load = np.reshape(P_Load, (len(load_buses), 1))
    Q_load = np.reshape(Q_Load, (len(load_buses), 1))

    return P_load, Q_load

# Example usage:
baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()
#convert_branch(baseMVA, bus, branch)
convert_loads(bus)
P_load, Q_load = calculate_just_loads(baseMVA, bus)

# Now you can use P_load, Q_load, and other modified arrays as needed.

# High Load Scenario Genration

In [6]:
import numpy as np

N = 30  # Number of scenarios for high loads
k_values_positive = np.arange(1, 2.00001, 1/14)
k_values_negative = -np.flip(k_values_positive)  # Generate negative values by flipping the positive ones

k_values = np.concatenate(( k_values_negative, k_values_positive))

def generate_high_load_scenarios(P_load, Q_load, N, k_values):
    # Initialize the scenarios matrix
    P_load_scenarios = np.zeros((N, P_load.shape[0]))
    Q_load_scenarios = np.zeros((N, Q_load.shape[0]))

    # For every non-zero element in P_load, generate N scenarios for high loads with specified k values.
    for idx in range(P_load.shape[0]):
        if P_load[idx, 0] != 0:
            for i, k in enumerate(k_values[:N]):
                P_load_scenarios[i, idx] = k * P_load[idx, 0]
                Q_load_scenarios[i, idx] = k * Q_load[idx, 0]

    return P_load_scenarios, Q_load_scenarios


P_load_high_scenarios, Q_load_high_scenarios = generate_high_load_scenarios(P_load, Q_load, N, k_values)

np.save(f"{PATH}/data/High_P_load_scenarios_{TEST_CASE}bus.npy", P_load_high_scenarios)
np.save(f"{PATH}/data/High_Q_load_scenarios_{TEST_CASE}bus.npy", Q_load_high_scenarios)

# Compute Injection scenarios

In [4]:
import numpy as np
import pandas as pd
import array
import csv
import math
import os.path
import random
import time
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus
PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"


TEST_CASE           =   '_small'
#TEST_CASE = '33bw_mod'
#TEST_CASE           =   'small_negload'
TEST_CASE           =   '906'


def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")
    bus = mat['ans']['bus'][0][0]
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc


def load_gen_data(filename):
    gen_data = pd.read_csv(filename, sep=',')
    return gen_data


def process_bus_and_gen(bus, gen, baseMVA, branch, ppc):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses=Just_load[:,0]
    load_buses=np.reshape(load_buses,(len(load_buses),1))

    n_buses = len(ppc['bus'])
    n_gens = len(ppc['gen'])
    n_branches = len(ppc['branch'])
    r = branch[:, 2]
    x = branch[:, 3]
    gen_buses = gen[:, 0]
    gen_values = gen[:, 1]
    Q_values = gen[:, 2]


    Pgen = np.zeros(n_buses)
    Qgen = np.zeros(n_buses)

    for i in range(len(gen_buses)):
        bus_idx = int(gen_buses[i])  
        Pgen[bus_idx] += gen_values[i]
        Qgen[bus_idx] += Q_values[i]

    #Depends on ...    
    Pgen  = Pgen / baseMVA
    Qgen  = Qgen / baseMVA

    Pgen = np.reshape(Pgen,(n_buses,1))    
    Qgen = np.reshape(Qgen,(n_buses,1))    

    ref_bus = np.where(bus[:, 1] == 3)[0][0]

    return load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus


baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()
load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

def compute_and_save_pinj():
    
    baseMVA, bus, gen, branch, _, _, _, ppc = load_mat()
    P_load_all_scenarios = np.load(f"{PATH}/data/P_load_all_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)
    Q_load_all_scenarios = np.load(f"{PATH}/data/Q_load_all_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)

    load_buses, n_buses, _, _, _, _, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

    # Pre-calculate P_inj for all scenarios
    P_inj_all_scenarios = []
    for s in range(P_load_all_scenarios.shape[0]): 
    #for s in range(P_load_all_scenarios.shape[1]-1): 
        aaa = P_load_all_scenarios[s, :]
        #aaa = P_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        P_inj = Pgen - Demand
        P_inj = np.delete(P_inj, ref_bus, 0)
        P_inj = np.asmatrix(P_inj)
        P_inj_all_scenarios.append(P_inj)
        
    Q_inj_all_scenarios = []
    for s in range(Q_load_all_scenarios.shape[0]): 
    #for s in range(Q_load_all_scenarios.shape[1]-1): 
        aaa = Q_load_all_scenarios[s, :]
        #aaa = Q_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        Q_inj = Qgen - Demand
        Q_inj = np.delete(Q_inj, ref_bus, 0)
        Q_inj = np.asmatrix(Q_inj)
        Q_inj_all_scenarios.append(Q_inj)        
        
    # Save to npy file
    np.save(f"{PATH}/data/P_inj_all_scenarios_{TEST_CASE}bus.npy", P_inj_all_scenarios)
    np.save(f"{PATH}/data/Q_inj_all_scenarios_{TEST_CASE}bus.npy", Q_inj_all_scenarios)

# Call the function
compute_and_save_pinj()

In [11]:
P_inj_all_scenarios = np.load(f"{PATH}/data/P_inj_all_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)
P_inj_all_scenarios[0]

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-8.68220207e-04],
       [-9.59902457e-05],
       [ 3.84844814e-04],
       [-8.00638846e-04],
       [-1.12711683e-04],
       [-3.13607287e-04],
       [-2.67926083e-04],
       [-7.27142891e-04],
       [-5.40028451e-04],
       [-1.08822453e-04],
       [-2.03369392e-04],
       [-8.01919529e-04],
       [-1.71823109e-04],
       [-9.38996320e-04],
       [-6.65431347e-04],
       [-1.86568332e-04],
       [-2.80324139e-03],
       [-8.72556702e-03],
       [-2.11895758e-03],
       [-3.25567702e-03],
       [-2.32902630e-03],
       [-1.92022019e-04],
       [-1.15284015e-02],
       [-1.16368563e-03],
       [-8.33106891e-03],
       [ 0.00000000e+00],
       [-2.32436012e-03],
       [-4.69643710e-03],
       [-8.38429860e-03],
       [-7.90471175e-03],
       [-4.68360706e-03],
       [ 0.00000000e+00],
       [-9.53097455e-03],
       [-1.76041597e-03],
       [-8.5

# High Load injection scenarios

In [7]:
import numpy as np
import pandas as pd
import array
import csv
import math
import os.path
import random
import time
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus
PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"


TEST_CASE           =   '906'


def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")
    bus = mat['ans']['bus'][0][0]
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc


def load_gen_data(filename):
    gen_data = pd.read_csv(filename, sep=',')
    return gen_data


def process_bus_and_gen(bus, gen, baseMVA, branch, ppc):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses=Just_load[:,0]
    load_buses=np.reshape(load_buses,(len(load_buses),1))

    n_buses = len(ppc['bus'])
    n_gens = len(ppc['gen'])
    n_branches = len(ppc['branch'])
    r = branch[:, 2]
    x = branch[:, 3]
    gen_buses = gen[:, 0]
    gen_values = gen[:, 1]
    Q_values = gen[:, 2]


    Pgen = np.zeros(n_buses)
    Qgen = np.zeros(n_buses)

    for i in range(len(gen_buses)):
        bus_idx = int(gen_buses[i])  
        Pgen[bus_idx] += gen_values[i]
        Qgen[bus_idx] += Q_values[i]

    #Depends on ...    
    Pgen  = Pgen / baseMVA
    Qgen  = Qgen / baseMVA

    Pgen = np.reshape(Pgen,(n_buses,1))    
    Qgen = np.reshape(Qgen,(n_buses,1))    

    ref_bus = np.where(bus[:, 1] == 3)[0][0]

    return load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus


baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()
load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

def compute_and_save_pinj():
    
    baseMVA, bus, gen, branch, _, _, _, ppc = load_mat()
    P_load_all_scenarios = np.load(f"{PATH}/data/High_P_load_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)
    Q_load_all_scenarios = np.load(f"{PATH}/data/High_Q_load_scenarios_{TEST_CASE}bus.npy", allow_pickle=True)

    load_buses, n_buses, _, _, _, _, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

    # Pre-calculate P_inj for all scenarios
    P_inj_all_scenarios = []
    for s in range(P_load_all_scenarios.shape[0]): 
    #for s in range(P_load_all_scenarios.shape[1]-1): 
        aaa = P_load_all_scenarios[s, :]
        #aaa = P_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        P_inj = Pgen - Demand
        P_inj = np.delete(P_inj, ref_bus, 0)
        P_inj = np.asmatrix(P_inj)
        P_inj_all_scenarios.append(P_inj)
        
    Q_inj_all_scenarios = []
    for s in range(Q_load_all_scenarios.shape[0]): 
    #for s in range(Q_load_all_scenarios.shape[1]-1): 
        aaa = Q_load_all_scenarios[s, :]
        #aaa = Q_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        Q_inj = Qgen - Demand
        Q_inj = np.delete(Q_inj, ref_bus, 0)
        Q_inj = np.asmatrix(Q_inj)
        Q_inj_all_scenarios.append(Q_inj)        
        
    # Save to npy file
    np.save(f"{PATH}/data/High_P_inj_all_scenarios_{TEST_CASE}bus.npy", P_inj_all_scenarios)
    np.save(f"{PATH}/data/High_Q_inj_all_scenarios_{TEST_CASE}bus.npy", Q_inj_all_scenarios)

# Call the function
compute_and_save_pinj()

# Uniform scenarios

In [8]:
import numpy as np

N = 10000

def generate_scenarios_uniform(P_load, Q_load, N):
    # Calculate the initial power factor
    power_factor = P_load / np.sqrt(P_load**2 + Q_load**2)

    # Initialize the scenarios matrix
    P_load_scenarios = np.zeros((N, P_load.shape[0]))
    Q_load_scenarios = np.zeros((N, Q_load.shape[0]))

    # For every non-zero element in P_load, generate N scenarios.
    # Draw random load values from a uniform distribution in the interval (1.5 * P_load, 0)
    for idx in range(P_load.shape[0]):
        if P_load[idx, 0] != 0:
            P_load_scenarios[:, idx] = np.random.uniform(0, 1.5 * P_load[idx, 0], N)
            # Calculate Q for each P scenario while keeping power factor constant
            Q_load_scenarios[:, idx] = P_load_scenarios[:, idx] * np.tan(np.arccos(power_factor[idx, 0]))

    return P_load_scenarios, Q_load_scenarios

P_load_scenarios_uniform, Q_load_scenarios_uniform = generate_scenarios_uniform(P_load, Q_load, N)

np.save(f"{PATH}/data/P_load_all_scenarios_uniform_{TEST_CASE}bus.npy", P_load_scenarios_uniform)
np.save(f"{PATH}/data/Q_load_all_scenarios_uniform_{TEST_CASE}bus.npy", Q_load_scenarios_uniform)


In [9]:
import numpy as np
import pandas as pd
import array
import csv
import math
import os.path
import random
import time
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import scipy.io
from pypower.api import ext2int, int2ext, makeYbus
PATH = "/storage/home/hcoda1/6/btaheri6/p-dmolzahn6-0/DistFlow"


TEST_CASE           =   '906'


def load_mat():
    mat = scipy.io.loadmat(f"{PATH}/data/case{TEST_CASE}.mat")
    bus = mat['ans']['bus'][0][0]
    baseMVA = mat['ans']['baseMVA'][0][0][0][0]
    gen = mat['ans']['gen'][0][0]
    branch = mat['ans']['branch'][0][0]
    keys = ['baseMVA', 'bus', 'gen', 'branch']
    values = [baseMVA, bus, gen, branch]
    ppc = dict(zip(keys, values))
    ppc = ext2int(ppc)
    baseMVA, bus, gen, branch = ppc['baseMVA'], ppc['bus'], ppc['gen'], ppc['branch']
    Ybus, Yf, Yt = makeYbus(baseMVA, bus, branch)

    return baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc


def load_gen_data(filename):
    gen_data = pd.read_csv(filename, sep=',')
    return gen_data


def process_bus_and_gen(bus, gen, baseMVA, branch, ppc):
    Just_load = bus[np.logical_or(bus[:, 2] != 0, bus[:, 3] != 0)]
    load_buses=Just_load[:,0]
    load_buses=np.reshape(load_buses,(len(load_buses),1))

    n_buses = len(ppc['bus'])
    n_gens = len(ppc['gen'])
    n_branches = len(ppc['branch'])
    r = branch[:, 2]
    x = branch[:, 3]
    gen_buses = gen[:, 0]
    gen_values = gen[:, 1]
    Q_values = gen[:, 2]


    Pgen = np.zeros(n_buses)
    Qgen = np.zeros(n_buses)

    for i in range(len(gen_buses)):
        bus_idx = int(gen_buses[i])  
        Pgen[bus_idx] += gen_values[i]
        Qgen[bus_idx] += Q_values[i]

    #Depends on ...    
    Pgen  = Pgen / baseMVA
    Qgen  = Qgen / baseMVA

    Pgen = np.reshape(Pgen,(n_buses,1))    
    Qgen = np.reshape(Qgen,(n_buses,1))    

    ref_bus = np.where(bus[:, 1] == 3)[0][0]

    return load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus


baseMVA, bus, gen, branch, Ybus, Yf, Yt, ppc = load_mat()
load_buses, n_buses, n_gens, n_branches, r, x, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

def compute_and_save_pinj():
    
    baseMVA, bus, gen, branch, _, _, _, ppc = load_mat()
    P_load_all_scenarios = np.load(f"{PATH}/data/P_load_all_scenarios_uniform_{TEST_CASE}bus.npy", allow_pickle=True)
    Q_load_all_scenarios = np.load(f"{PATH}/data/Q_load_all_scenarios_uniform_{TEST_CASE}bus.npy", allow_pickle=True)

    load_buses, n_buses, _, _, _, _, Pgen,Qgen, ref_bus = process_bus_and_gen(bus, gen, baseMVA, branch, ppc)

    # Pre-calculate P_inj for all scenarios
    P_inj_all_scenarios = []
    for s in range(P_load_all_scenarios.shape[0]): 
    #for s in range(P_load_all_scenarios.shape[1]-1): 
        aaa = P_load_all_scenarios[s, :]
        #aaa = P_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        P_inj = Pgen - Demand
        P_inj = np.delete(P_inj, ref_bus, 0)
        P_inj = np.asmatrix(P_inj)
        P_inj_all_scenarios.append(P_inj)
        
    Q_inj_all_scenarios = []
    for s in range(Q_load_all_scenarios.shape[0]): 
    #for s in range(Q_load_all_scenarios.shape[1]-1): 
        aaa = Q_load_all_scenarios[s, :]
        #aaa = Q_load_all_scenarios.iloc[:, s+1]

        Demand = np.zeros(n_buses)
        for i in range(len(load_buses)):
            #bus_idx = int(load_buses[i])
            bus_idx = int(load_buses[i][0])  # assuming load_buses[i] is a 1D array with one element

            Demand[bus_idx] = aaa[i]
        Demand = np.reshape(Demand, (n_buses, 1))
        Q_inj = Qgen - Demand
        Q_inj = np.delete(Q_inj, ref_bus, 0)
        Q_inj = np.asmatrix(Q_inj)
        Q_inj_all_scenarios.append(Q_inj)        
        
    # Save to npy file
    np.save(f"{PATH}/data/P_inj_all_scenarios_uniform_{TEST_CASE}bus.npy", P_inj_all_scenarios)
    np.save(f"{PATH}/data/Q_inj_all_scenarios_uniform_{TEST_CASE}bus.npy", Q_inj_all_scenarios)

# Call the function
compute_and_save_pinj()

In [2]:

import numpy as np
k_values_positive = np.arange(1, 2.00001, 1/14)
k_values_positive

array([1.        , 1.07142857, 1.14285714, 1.21428571, 1.28571429,
       1.35714286, 1.42857143, 1.5       , 1.57142857, 1.64285714,
       1.71428571, 1.78571429, 1.85714286, 1.92857143, 2.        ])